# Generated by Django 2.2.10 on 2020-02-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_sku_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_id', models.IntegerField()),
                ('product_sku_img', models.ImageField(upload_to='manufac/static/media/')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('r', 'Confirmed'), ('s', 'Started'), ('h', 'Halted'), ('c', 'Completed')], default='d', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Least')])),
                ('required_quantity', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('component_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufac.ComponentSku')),
            ],
        ),
        migrations.CreateModel(
            name='BomComponentSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_consumption', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufac.Bom')),
                ('fabric_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufac.ComponentSku')),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufac.WorkOrder')),
            ],
        ),
    ]
